# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b5cbc178dd5b6a05d022b38b5103878e"
name = "search_bar"
handle = "search_bar-2"
application_url = "https://violation-traditions-treated-herbal.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "development-store-2396.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://violation-traditions-treated-herbal.trycloudflare.com/auth/callback",
  "https://violation-traditions-treated-herbal.trycloudflare.com/auth/shopify/callback",
  "https://violation-traditions-treated-herbal.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
