# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f1e5c28469bdf4e1ab3836f5a80b4d62"
name = "Miro Extension"
handle = "miro_extension"
application_url = "https://strike-step-unless-characters.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-db2dc1d6.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://strike-step-unless-characters.trycloudflare.com/auth/callback",
  "https://strike-step-unless-characters.trycloudflare.com/auth/shopify/callback",
  "https://strike-step-unless-characters.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false

[app_preferences]
url = "https://miros-shopify-app-abffbc907e41.herokuapp.com/"
