# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f1e5c28469bdf4e1ab3836f5a80b4d62"
name = "searching_bar"
handle = "searching_bar"
application_url = "https://cameroon-clinton-proportion-workflow.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-db2dc1d6.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://cameroon-clinton-proportion-workflow.trycloudflare.com/auth/callback",
  "https://cameroon-clinton-proportion-workflow.trycloudflare.com/auth/shopify/callback",
  "https://cameroon-clinton-proportion-workflow.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
