# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a22a92b6335e92da0a9ef97f5a497ca2"
name = "Miro Staging"
handle = "miro-staging"
application_url = "https://media-pattern-beneath-occurring.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-db2dc1d6.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://media-pattern-beneath-occurring.trycloudflare.com/auth/callback",
  "https://media-pattern-beneath-occurring.trycloudflare.com/auth/shopify/callback",
  "https://media-pattern-beneath-occurring.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
